1) endpoint:
- def developer( desarrollador : str ): Cantidad de items y porcentaje de contenido Free por año según empresa desarrolladora. Ejemplo de retorno:
- Año	Cantidad de Items	Contenido Free
- 2023	50	27%
- 2022	45	25%
- xxxx	xx	xx%

In [9]:
import pandas as pd

# Leo el archivo que voy a utilizar para este endpoint
games = pd.read_parquet('../Dataset/games_clean.parquet')

In [10]:
games.head(10)

,id,title,developer,release_date,genres,tags,price
0,761140,Lost Summoner Kitty,Kotoshiro,2018-01-04,"Action, Casual, Indie, Simulation, Strategy","Strategy, Action, Indie, Casual, Simulation",4.99
1,643980,Ironbound,Secret Level SRL,2018-01-04,"Free to Play, Indie, RPG, Strategy","Free to Play, Strategy, Indie, RPG, Card Game,...",0.00
2,670290,Real Pool 3D - Poolians,Poolians.com,2017-07-24,"Casual, Free to Play, Indie, Simulation, Sports","Free to Play, Simulation, Sports, Casual, Indi...",0.00
3,767400,弹炸人2222,彼岸领域,2017-12-07,"Action, Adventure, Casual","Action, Adventure, Casual",0.99
4,772540,Battle Royale Trainer,Trickjump Games Ltd,2018-01-04,"Action, Adventure, Simulation","Action, Adventure, Simulation, FPS, Shooter, T...",3.99
5,774277,SNOW - All Access Pro Pass,Poppermost Productions,2018-01-04,"Free to Play, Indie, Simulation, Sports","Free to Play, Indie, Simulation, Sports",18.99
6,774278,SNOW - All Access Legend Pass,Poppermost Productions,2018-01-04,"Free to Play, Indie, Simulation, Sports","Free to Play, Indie, Simulation, Sports",29.99
7,770380,Army of Tentacles: (Not) A Cthulhu Dating Sim:...,Stegalosaurus Game Development,2018-01-04,"Action, Adventure, Casual, Indie, RPG","Action, Adventure, RPG, Indie, Casual",10.99
8,768880,Beach Rules,Copperpick Studio,2018-01-04,"Casual, Indie","Casual, Indie, Pixel Graphics, Cute, 2D",3.99
9,765320,Planetarium 2 - Zen Odyssey,Ghulam Jewel,2018-01-03,"Casual, Indie, Simulation","Indie, Casual, Simulation",2.99

In [11]:
games = games[['developer', 'release_date', 'price']]
games.head(5)

             developer release_date  price
0            Kotoshiro   2018-01-04   4.99
1     Secret Level SRL   2018-01-04   0.00
2         Poolians.com   2017-07-24   0.00
3                 彼岸领域   2017-12-07   0.99
4  Trickjump Games Ltd   2018-01-04   3.99

In [12]:
#Creamos una columna de contenido free representado por 1 y no free por 0
games['free'] = games['price'].apply(lambda x: 1 if x == 0 else 0)

#Despues elimino la columna "price"
games.drop('price', axis=1, inplace=True)

# Revisamos los cambios
games.head(5)

             developer release_date  free
0            Kotoshiro   2018-01-04     0
1     Secret Level SRL   2018-01-04     1
2         Poolians.com   2017-07-24     1
3                 彼岸领域   2017-12-07     0
4  Trickjump Games Ltd   2018-01-04     0

In [13]:
#Exporto el archivo
games.to_parquet('../Dataset/developer.parquet', compression='snappy', index=False)