In [20]:
import pandas as pd

In [21]:
games = pd.read_parquet('../Dataset/games_sistem.parquet')

In [22]:
games.head()

,id,title,developer,release_date,genres,tags,price
0,761140,Lost Summoner Kitty,Kotoshiro,2018-01-04,"[Action, Casual, Indie, Simulation, Strategy]","[Strategy, Action, Indie, Casual, Simulation]",4.99
1,643980,Ironbound,Secret Level SRL,2018-01-04,"[Free to Play, Indie, RPG, Strategy]","[Free to Play, Strategy, Indie, RPG, Card Game...",0.00
2,670290,Real Pool 3D - Poolians,Poolians.com,2017-07-24,"[Casual, Free to Play, Indie, Simulation, Sports]","[Free to Play, Simulation, Sports, Casual, Ind...",0.00
3,767400,弹炸人2222,彼岸领域,2017-12-07,"[Action, Adventure, Casual]","[Action, Adventure, Casual]",0.99
4,772540,Battle Royale Trainer,Trickjump Games Ltd,2018-01-04,"[Action, Adventure, Simulation]","[Action, Adventure, Simulation, FPS, Shooter, ...",3.99

In [23]:
games = games.drop(games[games['id'] == "767400"].index)

In [24]:
# Proceso a desanidar la columna genres, para tener un genero por fila
games = games.explode(column='genres')

# Ahora voy a restablecer el índice del Df resultante y descartare el índice anterior
games = games.reset_index(drop=True)
games

,id,title,developer,release_date,genres,tags,price
0,761140,Lost Summoner Kitty,Kotoshiro,2018-01-04,Action,"[Strategy, Action, Indie, Casual, Simulation]",4.99
1,761140,Lost Summoner Kitty,Kotoshiro,2018-01-04,Casual,"[Strategy, Action, Indie, Casual, Simulation]",4.99
2,761140,Lost Summoner Kitty,Kotoshiro,2018-01-04,Indie,"[Strategy, Action, Indie, Casual, Simulation]",4.99
3,761140,Lost Summoner Kitty,Kotoshiro,2018-01-04,Simulation,"[Strategy, Action, Indie, Casual, Simulation]",4.99
4,761140,Lost Summoner Kitty,Kotoshiro,2018-01-04,Strategy,"[Strategy, Action, Indie, Casual, Simulation]",4.99
...,...,...,...,...,...,...,...
55604,610660,Russian Roads,Laush Dmitriy Sergeevich,2018-01-04,Indie,"[Indie, Simulation, Racing]",1.99
55605,610660,Russian Roads,Laush Dmitriy Sergeevich,2018-01-04,Racing,"[Indie, Simulation, Racing]",1.99
55606,610660,Russian Roads,Laush Dmitriy Sergeevich,2018-01-04,Simulation,"[Indie, Simulation, Racing]",1.99
55607,658870,EXIT 2 - Directions,"xropi,stev3ns",2017-09-02,Casual,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",4.99
55608,658870,EXIT 2 - Directions,"xropi,stev3ns",2017-09-02,Indie,"[Indie, Casual, Puzzle, Singleplayer, Atmosphe...",4.99

In [25]:
# Utilizo drop para sacar las columnas que no voy a utilizar
games.drop(['price', 'release_date','tags', 'developer'], axis=1, inplace=True)

In [26]:
games

           id                title      genres
0      761140  Lost Summoner Kitty      Action
1      761140  Lost Summoner Kitty      Casual
2      761140  Lost Summoner Kitty       Indie
3      761140  Lost Summoner Kitty  Simulation
4      761140  Lost Summoner Kitty    Strategy
...       ...                  ...         ...
55604  610660        Russian Roads       Indie
55605  610660        Russian Roads      Racing
55606  610660        Russian Roads  Simulation
55607  658870  EXIT 2 - Directions      Casual
55608  658870  EXIT 2 - Directions       Indie

[55609 rows x 3 columns]

In [27]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55609 entries, 0 to 55608
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      55609 non-null  object
 1   title   55609 non-null  object
 2   genres  55609 non-null  object
dtypes: object(3)
memory usage: 1.3+ MB

In [28]:
games.shape

(55609, 3)

In [29]:
# Eliminación de duplicados
games.drop_duplicates(subset='title', keep='first', inplace=True)

In [30]:
games.duplicated().sum()

0

In [31]:
games.head(15)

        id                                              title        genres
0   761140                                Lost Summoner Kitty        Action
5   643980                                          Ironbound  Free to Play
9   670290                            Real Pool 3D - Poolians        Casual
14  772540                              Battle Royale Trainer        Action
17  774277                         SNOW - All Access Pro Pass  Free to Play
21  774278                      SNOW - All Access Legend Pass  Free to Play
25  770380  Army of Tentacles: (Not) A Cthulhu Dating Sim:...        Action
30  768880                                        Beach Rules        Casual
32  765320                        Planetarium 2 - Zen Odyssey        Casual
35  773650                            The first thrust of God     Adventure
40  774271                                SNOW - Starter Pack  Free to Play
44  773690            The first thrust of God - All Aircrafts     Adventure
49  774279                               SNOW - Lifetime Pack  Free to Play
53  768060                           The Warrior Of Treasures        Action
56  775880                       RC Plane 3 - Canyon Scenario        Racing

In [32]:
games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 22512 entries, 0 to 55607
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      22512 non-null  object
 1   title   22512 non-null  object
 2   genres  22512 non-null  object
dtypes: object(3)
memory usage: 703.5+ KB

In [33]:
# Guardamos el dataset en parquet 
games.to_parquet('../Dataset/game_recommendation.parquet', compression='snappy', index=False)

-------------------------------------------------------------------------------------------------------------------------

# Prueba del Modelo

In [ ]:
import pandas as pd

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
def recomendacion_juego(id_de_producto: int):
    
    games = pd.read_parquet('../Dataset/game_recommendation.parquet')

    id_de_producto = str(id_de_producto)
    games['id'] = games['id'].astype(str)

    atributos = games[games['id'] == id_de_producto]
    
    if atributos.empty:
        return 'No se encontró un juego con el ID proporcionado, prueba otro ID.'
    
    juegos = games[games['genres'] == atributos['genres'].iloc[0]]
    juegos= juegos[['title','genres']]
    juegos['caracteristicas'] = juegos[['genres']].apply(lambda row: '-'.join(row.values.astype(str)), axis=1) 
    juegos= juegos[['title','caracteristicas']].iloc[:1001,:]
    
    vector= TfidfVectorizer()
    matriz= vector.fit_transform(juegos['caracteristicas'])
    matriz_similaridad= cosine_similarity(matriz)
    
    indice_juego = juegos.index[juegos['title'] == atributos['title'].iloc[0]].tolist()[0]
    similares = list(enumerate(matriz_similaridad[indice_juego]))
    similaridades = sorted(similares, key=lambda x: x[1], reverse=True)[1:6]
    juegos_recomendados = [juegos.iloc[i[0]]['title'] for i in similaridades]

    return {'Juegos similares que te pueden interesar': juegos_recomendados}
recomendacion_juego("1640")

{'Juegos similares que te pueden interesar': ['Disciples II: Rise of the Elves',
  'Ghost Master®',
  'Vegas: Make It Big™',
  'CivCity: Rome',
  'Civilization IV®: Warlords']}